// Generate seed SQL from fitness_exercises_300_ru.json.
// Run: go run ./scripts/generate_seed
// Output: migrations/000013_seed_fitness_data.up.sql
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type ExerciseRU struct {
	ID              string             `json:"id"`
	Name            string             `json:"название"`
	MuscleGroup     string             `json:"группа_мышц"`
	Equipment       []string           `json:"оборудование"`
	Tags            []string           `json:"теги"`
	Description     string             `json:"описание"`
	Instruction     []string           `json:"инструкция"`
	Muscles         []string           `json:"мышцы"`
	MuscleLoads     map[string]float64 `json:"нагрузка_по_мышцам"`
	Formula         string             `json:"формула"`
	DifficultyLevel string             `json:"уровень_сложности"`
	IsBase          bool               `json:"базовое"`
	IsPopular       bool               `json:"популярное"`
	IsFree          bool               `json:"бесплатное"`
}

type ProgramRU struct {
	ID          string `json:"id"`
	Name        string `json:"название"`
	Description string `json:"описание"`
}

type ProgramExerciseLinkRU struct {
	ProgramID  string `json:"программа_id"`
	ExerciseID string `json:"упражнение_id"`
	Order      int    `json:"порядок"`
}

type FitnessJSON struct {
	Exercises []ExerciseRU          `json:"упражнения"`
	Programs  []ProgramRU           `json:"программы"`
	Links     []ProgramExerciseLinkRU `json:"связи_программа_упражнение"`
}

func escapeSQL(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, `\`, `\\`), `'`, `''`)
}

func arrToSQL(arr []string) string {
	if len(arr) == 0 {
		return "'{}'"
	}
	parts := make([]string, len(arr))
	for i, v := range arr {
		parts[i] = `'` + escapeSQL(v) + `'`
	}
	return `ARRAY[` + strings.Join(parts, ",") + `]::TEXT[]`
}

func jsonObjToSQL(m map[string]float64) string {
	if len(m) == 0 {
		return `'{}'::jsonb`
	}
	parts := make([]string, 0, len(m))
	for k, v := range m {
		parts = append(parts, fmt.Sprintf(`"%s":%.4f`, escapeSQL(k), v))
	}
	return `'` + strings.ReplaceAll(`{`+strings.Join(parts, ",")+`}`, `'`, `''`) + `'::jsonb`
}

func main() {
	base := filepath.Join("files", "fitness_exercises_300_ru.json")
	data, err := os.ReadFile(base)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read JSON: %v\n", err)
		os.Exit(1)
	}
	var j FitnessJSON
	if err := json.Unmarshal(data, &j); err != nil {
		fmt.Fprintf(os.Stderr, "parse JSON: %v\n", err)
		os.Exit(1)
	}

	out := &strings.Builder{}
	out.WriteString("-- FITFLOW: Seed fitness data from fitness_exercises_300_ru.json\n")
	out.WriteString("-- Generated by: go run ./scripts/generate_seed\n\n")

	// 1. Muscles
	muscleSet := make(map[string]struct{})
	for _, ex := range j.Exercises {
		for _, m := range ex.Muscles {
			if m != "" {
				muscleSet[m] = struct{}{}
			}
		}
	}
	if len(muscleSet) > 0 {
		out.WriteString("INSERT INTO muscles (name) VALUES\n")
		first := true
		for name := range muscleSet {
			if !first {
				out.WriteString(",\n")
			}
			first = false
			out.WriteString("  ('" + escapeSQL(name) + "')")
		}
		out.WriteString("\nON CONFLICT (name) DO NOTHING;\n\n")
	}

	// 2. Exercises
	out.WriteString("INSERT INTO exercises (id, name, muscle_group, equipment, tags, description, instruction, muscle_loads, formula, difficulty_level, is_base, is_popular, is_free)\nVALUES\n")
	for i, ex := range j.Exercises {
		if i > 0 {
			out.WriteString(",\n")
		}
		mg := "NULL"
		if ex.MuscleGroup != "" {
			mg = "'" + escapeSQL(ex.MuscleGroup) + "'"
		}
		desc := "NULL"
		if ex.Description != "" {
			desc = "'" + escapeSQL(ex.Description) + "'"
		}
		formula := "NULL"
		if ex.Formula != "" {
			formula = "'" + escapeSQL(ex.Formula) + "'"
		}
		diff := "NULL"
		if ex.DifficultyLevel != "" {
			diff = "'" + escapeSQL(ex.DifficultyLevel) + "'"
		}
		fmt.Fprintf(out, "  ('%s', '%s', %s, %s, %s, %s, %s, %s, %s, %s, %v, %v, %v)",
			ex.ID, escapeSQL(ex.Name), mg,
			arrToSQL(ex.Equipment), arrToSQL(ex.Tags), desc,
			arrToSQL(ex.Instruction), jsonObjToSQL(ex.MuscleLoads), formula, diff,
			ex.IsBase, ex.IsPopular, ex.IsFree)
	}
	out.WriteString("\nON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, muscle_group = EXCLUDED.muscle_group, equipment = EXCLUDED.equipment, tags = EXCLUDED.tags, description = EXCLUDED.description, instruction = EXCLUDED.instruction, muscle_loads = EXCLUDED.muscle_loads, formula = EXCLUDED.formula, difficulty_level = EXCLUDED.difficulty_level, is_base = EXCLUDED.is_base, is_popular = EXCLUDED.is_popular, is_free = EXCLUDED.is_free;\n\n")

	// 3. exercise_muscles: insert via SELECT joining muscles by name
	out.WriteString("INSERT INTO exercise_muscles (exercise_id, muscle_id, load_share)\nSELECT v.exercise_id, m.id, v.load_share FROM (VALUES\n")
	seen := make(map[string]bool)
	var rows []string
	for _, ex := range j.Exercises {
		for _, mn := range ex.Muscles {
			if mn == "" {
				continue
			}
			load := 1.0
			if ex.MuscleLoads != nil {
				if v, ok := ex.MuscleLoads[mn]; ok {
					load = v
				}
			}
			key := ex.ID + ":" + mn
			if seen[key] {
				continue
			}
			seen[key] = true
			rows = append(rows, fmt.Sprintf("  ('%s'::uuid, '%s', %.4f)", ex.ID, escapeSQL(mn), load))
		}
	}
	out.WriteString(strings.Join(rows, ",\n"))
	out.WriteString("\n) AS v(exercise_id, muscle_name, load_share)\nJOIN muscles m ON m.name = v.muscle_name\nON CONFLICT (exercise_id, muscle_id) DO UPDATE SET load_share = EXCLUDED.load_share;\n\n")

	// 4. Programs
	out.WriteString("INSERT INTO programs (id, name, description) VALUES\n")
	for i, p := range j.Programs {
		if i > 0 {
			out.WriteString(",\n")
		}
		desc := "NULL"
		if p.Description != "" {
			desc = "'" + escapeSQL(p.Description) + "'"
		}
		fmt.Fprintf(out, "  ('%s', '%s', %s)", p.ID, escapeSQL(p.Name), desc)
	}
	out.WriteString("\nON CONFLICT (id) DO NOTHING;\n")

	// 5. program_exercises
	out.WriteString("\nINSERT INTO program_exercises (program_id, exercise_id, order_index) VALUES\n")
	for i, link := range j.Links {
		if i > 0 {
			out.WriteString(",\n")
		}
		fmt.Fprintf(out, "  ('%s', '%s', %d)", link.ProgramID, link.ExerciseID, link.Order)
	}
	out.WriteString("\nON CONFLICT (program_id, exercise_id) DO UPDATE SET order_index = EXCLUDED.order_index;\n")

	dest := filepath.Join("migrations", "000013_seed_fitness_data.up.sql")
	if err := os.WriteFile(dest, []byte(out.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write migration: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated", dest)
}
