name: fitflow
description: GymMore — fitness app (gymmore.ru). Mobile and web client.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  go_router: ^14.2.0
  image_picker: ^1.0.7
  http_parser: ^4.0.2
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/colors.json
